/**
 * Regenerates `tests/stress.fixtures.ts`, the scale fixtures for the type-level
 * machinery: a wide tree (60 sections x 21 routes = 1,260 routes) and a deep
 * tree (30 nested levels). Deterministic — run it after changing the shapes:
 *
 *   node tests/generate-stress.mjs
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const SECTIONS = 60;
const CHILDREN = 4;
const GRANDCHILDREN = 4;
const DEPTH = 30;

const indent = (level) => '  '.repeat(level);

const wideSection = (s) => {
  const lines = [];
  const icon = s % 3 === 0 ? `, icon: 'star'` : '';
  lines.push(`${indent(1)}section${s}: {`);
  lines.push(`${indent(2)}_metadata: { title: 'Section ${s}'${icon} },`);

  for (let c = 1; c <= CHILDREN; c += 1) {
    const key = c === 1 ? `'[id]'` : `child${c}`;
    const title = c === 1 ? `Section ${s} detail` : `Section ${s} child ${c}`;
    lines.push(`${indent(2)}${key}: {`);
    lines.push(`${indent(3)}_metadata: { title: '${title}' },`);
    for (let g = 1; g <= GRANDCHILDREN; g += 1) {
      lines.push(`${indent(3)}leaf${g}: { _metadata: { title: '${title} leaf ${g}' } },`);
    }
    lines.push(`${indent(2)}},`);
  }

  lines.push(`${indent(1)}},`);
  return lines.join('\n');
};

const deepLevels = () => {
  const open = [];
  const close = [];
  for (let level = 1; level <= DEPTH; level += 1) {
    open.push(`${indent(level)}l${level}: {`);
    open.push(`${indent(level + 1)}_metadata: { title: 'Level ${level}' },`);
    close.unshift(`${indent(level)}},`);
  }
  return [...open, ...close].join('\n');
};

/*
 * An app-sized tree the way a real one is usually split: a shared package declares the
 * structure and schemas with core's `defineRoutes`, and the app attaches its typed
 * metadata with `attachMetadata(...).withMeta<AppMeta, AuthContext>()`. 110 routes, 5 levels.
 */
const APP_SECTIONS = 5;
const APP_CHILDREN = ['[id]', 'settings', 'reports'];
const APP_GRANDCHILDREN = ['overview', '[tab]'];

const appKey = (pathname) => `NAV${pathname.replace(/[^a-z0-9]+/gi, '_').toUpperCase()}`;

const appTree = () => {
  const lines = [];
  const paths = [];

  const node = (level, key, pathname, metadata, body) => {
    paths.push(pathname);
    lines.push(`${indent(level)}${key.startsWith('[') ? `'${key}'` : key}: {`);
    lines.push(`${indent(level + 1)}_metadata: ${metadata ? `{ ${metadata} }` : '{}'},`);
    body();
    lines.push(`${indent(level)}},`);
  };

  for (let s = 1; s <= APP_SECTIONS; s += 1) {
    const section = `/section${s}`;
    node(1, `section${s}`, section, `searchParamsSchema: z.object({ q: z.string().optional(), page: z.number().default(1) })`, () => {
      for (const child of APP_CHILDREN) {
        const childPath = `${section}/${child}`;
        node(2, child, childPath, child === '[id]' ? 'paramSchema: z.number()' : '', () => {
          for (const grandchild of APP_GRANDCHILDREN) {
            const grandchildPath = `${childPath}/${grandchild}`;
            node(3, grandchild, grandchildPath, '', () => {
              node(4, 'history', `${grandchildPath}/history`, '', () => {
                node(5, 'entry', `${grandchildPath}/history/entry`, '', () => {});
              });
            });
          }
        });
      }
    });
  }

  return { lines: lines.join('\n'), paths };
};

const app = appTree();

const appPatch = app.paths
  .map((pathname, i) => {
    const icon = i % 4 === 0 ? `, icon: 'star'` : '';
    const accessible = pathname.endsWith('/settings') ? ', accessible: (ctx) => ctx.isAdmin' : '';
    return `${indent(1)}'${pathname}': { title: '${appKey(pathname)}'${icon}${accessible} },`;
  })
  .join('\n');

const file = `import { attachMetadata, defineRoutes } from '@hyeonqyu/typed-router-core';
import { z } from 'zod';

/**
 * Generated by \`node tests/generate-stress.mjs\` — do not edit by hand.
 *
 * Scale fixtures for the type-level machinery. \`stress.types.test-d.ts\` asserts
 * against them so that width (${SECTIONS * (1 + CHILDREN + CHILDREN * GRANDCHILDREN)} routes) and depth (${DEPTH} levels) keep
 * compiling; \`tsc --extendedDiagnostics -p tests/tsconfig.json\` is the tool for
 * comparing the cost before and after touching the machinery. \`appRoutes\` is the
 * app-sized case (${app.paths.length} routes, 5 levels, typed metadata) the adapters' \`bindRoutes\`
 * must infer without an explicit type argument.
 */
export const wideRoutes = defineRoutes({
${Array.from({ length: SECTIONS }, (_, i) => wideSection(i + 1)).join('\n')}
});

export const deepRoutes = defineRoutes({
${deepLevels()}
});

const appBaseRoutes = defineRoutes({
${app.lines}
});

export type AppTranslationKey =
${app.paths.map((pathname) => `  | '${appKey(pathname)}'`).join('\n')};
export type AppMeta = { title: AppTranslationKey; icon?: 'star' | 'gear'; roles?: readonly ('admin' | 'member')[] };
export type AuthContext = { isAdmin: boolean };

export const appRoutes = attachMetadata(appBaseRoutes).withMeta<AppMeta, AuthContext>()({
${appPatch}
});

export type WideRoutes = typeof wideRoutes;
export type DeepRoutes = typeof deepRoutes;
export type AppRoutes = typeof appRoutes;
`;

const out = join(dirname(fileURLToPath(import.meta.url)), 'stress.fixtures.ts');
writeFileSync(out, file);
console.log(
  `wrote ${out}: ${SECTIONS * (1 + CHILDREN + CHILDREN * GRANDCHILDREN)} wide routes, ${DEPTH} deep levels, ${app.paths.length} app routes`,
);
